name: Code Validation
on: [push]

env:
  NPM_REGISTRY_URL: ${{ secrets.NPM_REGISTRY_URL }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  FAKE_VAR: ${{ secrets.FAKE_VAR }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: debug vars
        run: |
          echo "$FAKE_VAR"
      - name: Install dependencies
        run: npm install -g yarn && yarn        
      - name: Lint        
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Coverage
        run: yarn coverage