name: Code Validation
on: [push]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install -g yarn && yarn
        env:
            NPM_REGISTRY_URL: ${{ secrets.NPM_REGISTRY_URL }}
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Lint        
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Coverage
        run: yarn coverage