name: Code Validation
on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}\n@demandio:registry=${{ secrets.NPM_REGISTRY_URL }}" > ~/.npmrc
          npm install -g yarn && yarn        
      - name: Lint        
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Coverage
        run: yarn coverage