name: Code Validation
on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}\n@demandio:registry=${NPM_REGISTRY_URL}" > ~/.npmrc
          npm install -g yarn && yarn        
        env:
          NPM_REGISTRY_URL: ${{ env.NPM_REGISTRY_URL }}
          NPM_AUTH_TOKEN: ${{ env.NPM_AUTH_TOKEN }}
      - name: Lint        
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Coverage
        run: yarn coverage